comicrelief/giftaid-react

package.json
src/App.scss
yarn.lock

- PL as dependency
- PL imports

pattern lab dependency

---

package.json
src/components/App/App.js
yarn.lock

Include the cookie consent component

Added the cookie consent message component

---

src/pages/GiftAidForm/GiftAidForm.js

fix: updating trans source variable

---

src/pages/GiftAidForm/GiftAidForm.js

Route api errors to sorry page

Route api errors to sorry

---

tests/feature/giftaid-sanity/e2e.js

Removed gift aid check box click

fix sanity test fail

---

README.md
src/pages/GiftAidForm/GiftAidForm.js

Fixes https://github.com/comicrelief/serverless-giftaid/issues/17

17 campaign values

---

src/pages/UpdateForm/UpdateForm.js

Update what's being posted to BE

---

.env.dist
.eslintrc
cypress/integration/mainGA_spec.js
cypress/integration/updateGA_spec.js
src/components/App/App.js
src/components/Routes/AppliedRoute.js
src/components/Routes/CompletedRoute.js
src/components/Routes/UpdateCompletedRoute.js
src/config/site.json
src/pages/GiftAidForm/GiftAidForm.js
src/pages/Success/Success.js
src/pages/UpdateForm/UpdateForm.js
src/pages/UpdateSuccess/UpdateSuccess.js
src/service/Site.service.js

117 direct access success page

---

cypress/integration/update_spec.js
package.json
src/pages/UpdateForm/UpdateForm.js
src/pages/UpdateForm/UpdateForm.scss
tests/feature/giftaid-sanity/update.js
yarn.lock

Fix #115 
- Validates non UUID / invalid strings parameters in the update url

115 update non UUID pattern

---

src/pages/GiftAidForm/GiftAidForm.js

Fixes #132 
It should be noted that submitting the form on componentUpdate is definitely not standard practice and should be avoided due to the way that react lifecycle events work.

Fix for tripple submission bug

---

cypress/integration/update_spec.js
package.json
src/pages/UpdateForm/UpdateForm.js
src/pages/UpdateForm/UpdateForm.scss
src/pages/UpdateForm/defaultUpdateFields.json
tests/feature/giftaid-sanity/update.js
yarn.lock

Fixes #115 - added lower case regex pattern
Fixes #140 - removes `transactionId` regex test

Added lower case alphabet range to regex pattern

---

cypress/integration/update_spec.js
src/pages/UpdateForm/UpdateForm.js
tests/feature/giftaid-sanity/update.js

Updates nightwatch and cypress update journey tests

Updates nightwatch and cypress tests

---

cypress/integration/submit_spec.js
package.json
src/pages/GiftAidForm/GiftAidForm.js
src/pages/GiftAidForm/GiftAidForm.scss
src/pages/GiftAidForm/marketingConsentData.json
tests/feature/giftaid-sanity/submit.js
yarn.lock

fixes: #107 
`getValidation` gets `validation` from marektingconsent component and should be a function.
Related storybook PR: https://github.com/comicrelief/storybook/pull/295

Marketing consent

---

src/pages/GiftAidForm/GiftAidForm.js
src/pages/UpdateForm/UpdateForm.js

Fixes #146 - unix timestamp for marketing preferences

Fixes unix timestamp for marketing preferences

---

package.json
yarn.lock

fixes #149 - bumped storybook version with updated postcode validation

fixes #149 - bumped storybook

---

src/pages/GiftAidForm/GiftAidForm.js

Fixes #151 
- Save mobile number value for phone number when `permissionPhone` is  YES

Fixes #151 - add phone number value if permission is set

---

.snyk
package.json
yarn.lock

Bumped storybook to get latest regex changes for the address and postcode fields

Bumped storybook

---

package.json
yarn.lock

email validation fix

---

package.json
yarn.lock

Fixes postcode field validations

Fixes postcode field validations

---

package.json
yarn.lock

Fixes #167 - manifest and lock files out of sync issues

Fixes #167 - manifest and lock files out of sync issues

---

src/pages/GiftAidForm/marketingConsentData.json

Fixes #170 - renamed marketing consent permission fields

Fixes #170 - renamed marketing consent permission fields

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
public/index.html
yarn.lock

Fixes #180 
Added Content Security Policy to meta tag
- Before fix:
- After fix

Added Content Security Policy to meta tag

---

src/pages/GiftAid/UpdateForm/defaultFormFields.js
src/pages/GiftAid/index.js
src/pages/GiftAid/utils/getValidations.js

Fixes #182 - email value is null

Fixes #182 - email value is null

---

src/pages/GiftAid/utils/validateForm.js

Fixes #185 - update form bug

---

src/pages/GiftAid/utils/validateForm.js

Fix validation to allow optional email field

---

src/pages/GiftAid/GiftAid.js
src/pages/GiftAid/utils/Utils.js

fixes: #196 - submit issue

---

src/components/App/App.js
src/pages/GiftAid/SubmitForm/SubmitForm.js
src/pages/GiftAid/utils/Utils.js

preview here: https://deploy-preview-200--giftaid-react.netlify.com/

gtm email tracking 

---

src/pages/GiftAid/UpdateForm/UpdateForm.js

Removed console log

---

src/pages/GiftAid/SubmitForm/SubmitFormFields.js
src/pages/GiftAid/UpdateForm/UpdateFormFields.js

giftaid checkbox label update

---

cypress/integration/update_spec.js
package.json
yarn.lock

Use new storybook contentful footer

---

config/webpack.config.dev.js
config/webpack.config.prod.js

Whitelist update 2.0

---

config/webpack.config.dev.js
config/webpack.config.prod.js
cypress.json
cypress/integration/update_spec.js
package.json
src/components/App/App.js
yarn.lock

Update Footer with 'fallback links' menu item props

---

config/webpack.config.dev.js
config/webpack.config.prod.js
src/components/App/App.js

Whitelist analytic scripts

---

cypress/integration/submit_spec.js
src/components/FormHeader/SubmitHeader/index.js
src/components/FormHeader/UpdateHeader/index.js
src/config/site.json
src/pages/GiftAid/SubmitForm/SubmitFormFields.js
src/pages/GiftAid/UpdateForm/UpdateFormFields.js

Update copy for big night in

---

src/components/App/App.js
src/components/App/FooterCopy.js
src/pages/GiftAid/SubmitForm/SubmitForm.js

Footer Updates (copy, social)

---

tests/feature/giftaid-sanity/submit.js

Fix tests with new markup

---

src/components/App/App.js
src/styles/App.scss

Tweak footer styles to suit big BNI copy

---

src/pages/GiftAid/SubmitForm/SubmitForm.js

Correct sitename var check

---

src/pages/Success/Success.js
src/pages/Success/ThankYou/GiftAidConfirmMessage/index.js
src/styles/Success.scss

Change Thankyou page if BNI

---

package.json
yarn.lock

Related to this https://github.com/comicrelief/giftaid-react/pull/251

Update storybook version

---

config/webpack.config.dev.js
src/pages/GiftAid/utils/Utils.js
src/pages/Success/ThankYou/index.js
tests/feature/giftaid-sanity/update.js

Fixes comicrelief/technology-planning#36

Integrate erp

---

src/config/site.json

Update campaign codes for comicrelief.com and rednoseday.com submissions to RND21

Update campaign codes in site config

---

src/pages/GiftAid/SubmitForm/SubmitFormFields.js

Andrew has requested an update to this text

Update mobile help text

---

cypress/integration/submit_spec.js
package.json
src/pages/GiftAid/utils/Utils.js
yarn.lock

Storybook MP, Inputfield and associated validation update

---

src/pages/GiftAid/SubmitForm/SubmitForm.js
src/pages/GiftAid/UpdateForm/UpdateForm.js

Update address labels

---

nightwatch.conf.js
package.json
tests/commands/form.js
yarn.lock

Addressing a number of higher and critical level dependency updates.

fix: Update dependencies

---

src/components/Buttons/FormButton/index.js
src/pages/GiftAid/GiftAid.js
src/pages/GiftAid/SubmitForm/SubmitForm.js

FIxes https://comicrelief.atlassian.net/browse/ENG-1755
Adds a state flag to prevent multiple submissions in the same session.

ENG-1755: prevent multiple submissions

---

src/config/site.json
tests/feature/submit/marketingPreferencesData.js

As per https://comicrelief.atlassian.net/browse/ENG-1941

Update all non-BNI sites to use new campaign code

---

cypress/integration/submit_spec.js
cypress/integration/update_spec.js
package.json
yarn.lock

Brings in some of the simpler improvements Dependabot and Snyk raised in the Storybook repo

Hackday storybook updates

---

cypress/integration/submit_spec.js
src/pages/GiftAid/SubmitForm/SubmitFormFields.js

https://comicrelief.atlassian.net/browse/ENG-2178

feat: ENG-2178: Update mobile field messaging

---

cypress/integration/submit_spec.js
package.json
src/pages/GiftAid/SubmitForm/marketingConsentData.js
src/styles/SubmitForm.scss
tests/feature/submit/address.js
tests/feature/submit/error.js
tests/feature/submit/marketingPreferencesData.js
tests/feature/submit/marketingPreferencesValidation.js
yarn.lock

[ENG-2236](https://comicrelief.atlassian.net/browse/ENG-2236)
[ENG-2236]: https://comicrelief.atlassian.net/browse/ENG-2236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-2236: MP update

---

src/pages/GiftAid/GiftAid.js
src/pages/GiftAid/utils/Utils.js

Fixes https://comicrelief.atlassian.net/browse/ENG-2305
As well as fixing the actual 'scroll' functionality, now the app will only scroll to the first error when attempting to submit the form, not during field updates.
https://deploy-preview-377--giftaid-react.netlify.app/

ENG-2305: Scroll-to-error UX improvement

---

src/config/site.json
tests/feature/submit/marketingPreferencesData.js

Campaign code update

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
src/styles/App.scss
yarn.lock

Removes PL as a dependency, use updated Storybook as new source

ENG-2597: Remove pattern lab

---

src/pages/GiftAid/SubmitForm/SubmitFormFields.js
src/pages/GiftAid/UpdateForm/UpdateFormFields.js
src/styles/SubmitForm.scss
src/styles/UpdateForm.scss

Fixes https://comicrelief.atlassian.net/browse/ENG-2896

ENG-2896: Update legal copy, and styles to suit

---

src/pages/GiftAid/UpdateForm/UpdateForm.js
src/styles/Tooltip.scss

Fixes https://comicrelief.atlassian.net/browse/ENG-2904
**Before:**
---
**After:**

ENG-2904: Reposition Update text to make sense

---

README.md
e2e/submit/addressValidation.spec.js
e2e/submit/internationalAddressesValidation.spec.js
e2e/submit/marketingPreferencesValidation.spec.js
e2e/submit/postcodeLookup.spec.js
e2e/update/formValidation.spec.js
e2e/update/internationalAddressesValidation.spec.js
e2e/utils/commands.js
package.json
playwright/tests/submit/addressValidation.spec.js
playwright/tests/submit/internationalAddressesValidation.spec.js
playwright/tests/submit/marketingPreferencesValidation.spec.js
playwright/tests/submit/postcodeLookup.spec.js
playwright/tests/update/formValidation.spec.js
playwright/tests/update/internationalAddressesValidation.spec.js
playwright/tests/utils/commands.js
src/pages/GiftAid/SubmitForm/marketingConsentData.js
src/styles/SubmitForm.scss
yarn.lock

Fixes https://comicrelief.atlassian.net/browse/ENG-2926

ENG-2926: Remove 'Post' Marketing Pref, tweak layout to suit

---

playwright/tests/submit/marketingPreferencesData.spec.js
src/pages/GiftAid/utils/Utils.js

Fixes: https://ci.services.comicrelief.com/teams/engineering/pipelines/service-giftaid/jobs/spa-feature-test/builds/84

Fix Marketing Prefs 'Post' data check in staging tests

---

config/webpack.config.dev.js
config/webpack.config.prod.js

Fixes https://comicrelief.atlassian.net/browse/ENG-3203

Allowlist GA urls

---

.github/workflows/main.yml

fix: Use non-deprecated version of upload-artifact
